version: '3.1'
services:
  postgresql_db:
    container_name: postgres-auction-backend
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres/auction-backend
      POSTGRES_DB: Auction
    ports:
      - "5432:5432"
  redis_db:
    container_name: redis-auction-backend
    image: redis
    ports:
      - '6379:6379'