version: '3.1'
services:
  api-service:
    container_name: auction-backend-api
    build: /auction-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_db:5432/Auction
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgresql_db:5432/Auction
      - SPRING_CACHE_HOST=redis_db
      - SPRING_CACHE_PORT=6379
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - postgresql_db
      - redis_db
  client-service:
    container_name: auction-frontend
    build: /auction-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-service
  postgresql_db:
    container_name: postgres-auction-backend
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres/auction-backend
      POSTGRES_DB: Auction
    ports:
      - "5432:5432"
  redis_db:
    container_name: redis-auction-backend
    image: redis
    ports:
      - '6379:6379'