CREATE TABLE public.role
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);

CREATE TABLE public."user"
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    username   VARCHAR(255),
    password   VARCHAR(255),
    role_id    BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uc_user_username UNIQUE (username),
    CONSTRAINT FK_USER_ON_ROLE_ID FOREIGN KEY (role_id) REFERENCES public.role (role_id)
);
