CREATE TABLE public.product
(
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name  VARCHAR(255),
    description   VARCHAR(255),
    start_price   DOUBLE PRECISION,
    current_price DOUBLE PRECISION,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE public.bid
(
    product_id   BIGINT NOT NULL,
    bid_id       VARCHAR(255) NOT NULL,
    bid_username VARCHAR(255),
    bid_price    DOUBLE PRECISION,
    bid_date     VARCHAR(255),
    CONSTRAINT "fk_bid_on_product" FOREIGN KEY (product_id) REFERENCES public.product (product_id)
);


